<script type="text/javascript" src="js/plugins/loaders/pace.min.js"></script>
    <script type="text/javascript" src="js/core/libraries/jquery.min.js"></script>
    <script type="text/javascript" src="js/core/libraries/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/plugins/notifications/pnotify.min.js"></script>
    <script type="text/javascript" src="js/pages/components_notifications_pnotify.js"></script>
    <script type="text/javascript" src="c5sc.js"></script>
    <script type="text/javascript" src="js/plugins/loaders/blockui.min.js"></script>
	<script type="text/javascript" src="js/plugins/forms/styling/switchery.min.js"></script>
	<script type="text/javascript" src="js/plugins/forms/styling/uniform.min.js"></script>
	<script type="text/javascript" src="js/plugins/forms/selects/bootstrap_multiselect.js"></script>
	<script type="text/javascript" src="js/plugins/ui/moment/moment.min.js"></script>
	<script type="text/javascript" src="js/plugins/pickers/daterangepicker.js"></script>
	<script type="text/javascript" src="js/plugins/ui/headroom/headroom.min.js"></script>
	<script type="text/javascript" src="js/plugins/ui/headroom/headroom_jquery.min.js"></script>
	<script type="text/javascript" src="js/core/app.js"></script>
	<script type="text/javascript" src="js/pages/dashboard.js"></script>
    <script type="text/javascript" src="js/pages/layout_navbar_main_hideable.js"></script>